from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import text  # ← додай це

# revision identifiers, used by Alembic.
revision = '16f46a5a10fb'
down_revision = '4f5f6c269815'
branch_labels = None
depends_on = None


def upgrade():
    # --- ДОДАЙ ЦЕ НАЙВЕРХУ upgrade() ---
    op.execute(text("ALTER TYPE priority_enum ADD VALUE IF NOT EXISTS 'medium';"))

    # --- решта як створив Alembic ---
    op.create_table('operator_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='operator_request_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('approved_by', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_operator_requests_approved_by_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operator_requests'))
    )
    op.create_index(op.f('ix_operator_requests_email'), 'operator_requests', ['email'], unique=True)
    op.drop_index(op.f('ix_answers_created_at'), table_name='answers')
    op.alter_column('comments', 'visibility',
               existing_type=postgresql.ENUM('public', 'internal', name='comment_visibility_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('questions', 'status',
               existing_type=postgresql.ENUM('new', 'answered', 'closed', name='question_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_questions_author_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_created_at'), table_name='questions')
    op.drop_index(op.f('ix_questions_status'), table_name='questions')
    op.alter_column('tickets', 'dept',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.alter_column('tickets', 'priority',
               existing_type=postgresql.ENUM('low', 'normal', 'high', name='priority_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tickets', 'status',
               existing_type=postgresql.ENUM('new', 'triage', 'in_progress', 'blocked', 'done', 'canceled', 'archived', 'pending_admin', name='ticket_status_enum'),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_tickets_dept'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_phone'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_topic'), table_name='tickets')
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('user', 'operator', 'admin', name='role_enum'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint(op.f('uq_users_email'), 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_users_email'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('user', 'operator', 'admin', name='role_enum'),
               server_default=sa.text("'user'::role_enum"),
               existing_nullable=False)
    op.create_index(op.f('ix_tickets_topic'), 'tickets', ['topic'], unique=False)
    op.create_index(op.f('ix_tickets_phone'), 'tickets', ['phone'], unique=False)
    op.create_index(op.f('ix_tickets_dept'), 'tickets', ['dept'], unique=False)
    op.alter_column('tickets', 'status',
               existing_type=postgresql.ENUM('new', 'triage', 'in_progress', 'blocked', 'done', 'canceled', 'archived', 'pending_admin', name='ticket_status_enum'),
               server_default=sa.text("'new'::ticket_status_enum"),
               existing_nullable=False)
    op.alter_column('tickets', 'priority',
               existing_type=postgresql.ENUM('low', 'normal', 'high', name='priority_enum'),
               server_default=sa.text("'normal'::priority_enum"),
               existing_nullable=False)
    op.alter_column('tickets', 'dept',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=64),
               existing_nullable=True)
    op.create_index(op.f('ix_questions_status'), 'questions', ['status'], unique=False)
    op.create_index(op.f('ix_questions_created_at'), 'questions', ['created_at'], unique=False)
    op.create_index(op.f('ix_questions_author_id'), 'questions', ['author_id'], unique=False)
    op.alter_column('questions', 'status',
               existing_type=postgresql.ENUM('new', 'answered', 'closed', name='question_status_enum'),
               server_default=sa.text("'new'::question_status_enum"),
               existing_nullable=False)
    op.alter_column('comments', 'visibility',
               existing_type=postgresql.ENUM('public', 'internal', name='comment_visibility_enum'),
               server_default=sa.text("'public'::comment_visibility_enum"),
               existing_nullable=False)
    op.create_index(op.f('ix_answers_created_at'), 'answers', ['created_at'], unique=False)
    op.drop_index(op.f('ix_operator_requests_email'), table_name='operator_requests')
    op.drop_table('operator_requests')
    # ### end Alembic commands ###
