"""operator feedback

Revision ID: 4b8b9625982f
Revises: 16f46a5a10fb
Create Date: 2025-11-13 14:01:06.551218
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b8b9625982f'
down_revision = '16f46a5a10fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operator_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operator_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_operator_feedback_author_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], name=op.f('fk_operator_feedback_operator_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operator_feedback'))
    )
    op.create_index(op.f('ix_operator_feedback_author_id'), 'operator_feedback', ['author_id'], unique=False)
    op.create_index(op.f('ix_operator_feedback_operator_id'), 'operator_feedback', ['operator_id'], unique=False)
    op.drop_index(op.f('ix_answers_question_created'), table_name='answers')
    op.drop_index(op.f('ix_questions_created'), table_name='questions')
    op.drop_index(op.f('ix_tickets_assignee'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_author'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_done_assignee_resolved'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_done_assignee_updated'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_resolved_at'), table_name='tickets')
    op.drop_index(op.f('ix_tickets_updated_at'), table_name='tickets')
    op.drop_index(op.f('ix_users_role_active'), table_name='users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_role_active'), 'users', ['role', 'is_active'], unique=False)
    op.create_index(op.f('ix_tickets_updated_at'), 'tickets', ['updated_at'], unique=False)
    op.create_index(op.f('ix_tickets_resolved_at'), 'tickets', ['resolved_at'], unique=False)
    op.create_index(op.f('ix_tickets_done_assignee_updated'), 'tickets', ['status', 'assignee_id', 'updated_at'], unique=False)
    op.create_index(op.f('ix_tickets_done_assignee_resolved'), 'tickets', ['status', 'assignee_id', 'resolved_at'], unique=False)
    op.create_index(op.f('ix_tickets_author'), 'tickets', ['author_id'], unique=False)
    op.create_index(op.f('ix_tickets_assignee'), 'tickets', ['assignee_id'], unique=False)
    op.create_index(op.f('ix_questions_created'), 'questions', ['created_at'], unique=False)
    op.create_index(op.f('ix_answers_question_created'), 'answers', ['question_id', 'created_at'], unique=False)
    op.drop_index(op.f('ix_operator_feedback_operator_id'), table_name='operator_feedback')
    op.drop_index(op.f('ix_operator_feedback_author_id'), table_name='operator_feedback')
    op.drop_table('operator_feedback')
    # ### end Alembic commands ###
